# Adding action from
# https://github.com/trsvchn/colab-badge-action

name: Open in Colab Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    name: Attact colab Action Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/master
      - name: Colab Badge Action 
        uses: trsvchn/colab-badge-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check: 'all'
          update: true
          target_branch: master
          target_repository: mnm-rnd/competitions
